name: Build and Push backend
on:
  workflow_run:
    workflows: [Test backend]
    types: [completed]
    push:
      branches:
        - master
      # to push only on changes in backend repo
      paths:
        - 'TP1/backend/**'

jobs:
  # define job to build and publish backend docker image
  build-and-push-docker-image-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    #on:
    #  push:
        
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # login to docker
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_ID }} -p ${{secrets.DOCKER_HUB_PWD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where backend source code with Dockerfile is located
          context: ./TP1/backend/simple-api-main/simple-api
          # Note: tags has to be all lower-case
          # donne un nom au conteneur
          tags:
            ${{secrets.DOCKER_HUB_ID}}/tp-devops-cpe:backend
          # push action (sur master)
          push: ${{ github.ref == 'refs/heads/master' }}